version: '3.4'

services:
  speller.presentation.web.api:
    image: ${DOCKER_REGISTRY-}spellerpresentationwebapi
    build:
      context: .
      dockerfile: Speller.Presentation.Web.Api/Dockerfile
